"""
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Runtime: 40 ms, faster than 84.44% of Python3 online submissions for Find the Difference.
Memory Usage: 13.1 MB, less than 5.00% of Python3 online submissions for Find the Difference.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        extra = 0
        for ch in s+t: extra ^= ord(ch)
        return chr(extra)
